name: Test ACR Push

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-acr-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Docker image
        run: |
          docker build -t test-image:latest .

      - name: Tag Docker image for ACR
        env:
          ACR_NAME: "classpathio"  # Use your ACR name
        run: |
          docker tag test-image:latest $ACR_NAME.azurecr.io/test-image:latest

      - name: Log in to ACR using Azure CLI
        env:
          ACR_NAME: "classpathio"  # Use your ACR name
        run: |
          az acr login --name $ACR_NAME

      - name: Push Docker image to ACR
        env:
          ACR_NAME: "classpathio"  # Use your ACR name
        run: |
          docker push $ACR_NAME.azurecr.io/test-image:latest
