name: Troubleshoot AADSTS500011 Error

on:
  workflow_dispatch:
    # Allows manual run from the Actions tab for troubleshooting.

permissions:
  id-token: write
  contents: read

jobs:
  troubleshoot-acr-access:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Log in to Azure CLI using OIDC
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 2: Verify Tenant ID from Azure CLI
      - name: Verify Azure CLI Tenant ID
        id: check-tenant-id
        run: |
          # Get the Tenant ID from Azure CLI after login
          CLI_TENANT_ID=$(az account show --query tenantId -o tsv)
          echo "CLI Tenant ID: $CLI_TENANT_ID"

          # Retrieve the Tenant ID from GitHub secrets
          SECRET_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          echo "GitHub Secret Tenant ID: $SECRET_TENANT_ID"

          # Compare the two Tenant IDs
          if [ "$CLI_TENANT_ID" = "$SECRET_TENANT_ID" ]; then
            echo "✅ Tenant IDs match."
          else
            echo "❌ Tenant IDs do not match."
            echo "CLI Tenant ID: $CLI_TENANT_ID"
            echo "GitHub Secret Tenant ID: $SECRET_TENANT_ID"
            exit 1
          fi

      # Step 3: Check if the Service Principal Can Access the ACR
      - name: List ACR Repositories
        id: list-acr
        env:
          ACR_NAME: "classpathio"  # Replace with your ACR name (e.g., 'classpathio')
        run: |
          echo "Testing access to Azure Container Registry (ACR) by listing repositories..."
          az acr repository list --name $ACR_NAME --output table
        continue-on-error: true  # Allows workflow to continue even if this fails
        # Note: If access is denied, the job will log the failure and continue to the next step.

      # Step 4: Check Role Assignments for the Service Principal on ACR
      - name: Verify AcrPush Role Assignment
        env:
          ACR_NAME: "classpathio"  # Replace with your ACR name
        run: |
          echo "Checking role assignments for the service principal on the ACR..."
          ROLE_ASSIGNMENTS=$(az role assignment list --assignee ${{ secrets.AZURE_CLIENT_ID }} --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/<your-resource-group>/providers/Microsoft.ContainerRegistry/registries/$ACR_NAME --query "[].roleDefinitionName" -o tsv)
          
          echo "Assigned Roles: $ROLE_ASSIGNMENTS"
          if echo "$ROLE_ASSIGNMENTS" | grep -q "AcrPush"; then
            echo "✅ The service principal has AcrPush role on ACR."
          else
            echo "❌ The service principal does NOT have AcrPush role on ACR."
            exit 1
          fi
